///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestRanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f1bf24fd-1ce0-44a5-8392-f9e2824547e4")]
    public partial class TestRanorexRepository : RepoGenBaseFolder
    {
        static TestRanorexRepository instance = new TestRanorexRepository();
        TestRanorexRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the TestRanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("f1bf24fd-1ce0-44a5-8392-f9e2824547e4")]
        public static TestRanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRanorexRepository() 
            : base("TestRanorexRepository", "/", null, 0, false, "f1bf24fd-1ce0-44a5-8392-f9e2824547e4", ".\\RepositoryImages\\TestRanorexRepositoryf1bf24fd.rximgres")
        {
            _applicationundertest = new TestRanorexRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f1bf24fd-1ce0-44a5-8392-f9e2824547e4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("1f687446-25e9-472e-87b2-1dbc3c883217")]
        public virtual TestRanorexRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestRanorexRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("1f687446-25e9-472e-87b2-1dbc3c883217")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "1f687446-25e9-472e-87b2-1dbc3c883217", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", ".//div[#'rx-header-fixed']/div//form/?/?/input[@type='text']", 30000, null, "26423bcd-90fe-4fa0-b814-57a75559dcef");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1f687446-25e9-472e-87b2-1dbc3c883217")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1f687446-25e9-472e-87b2-1dbc3c883217")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("26423bcd-90fe-4fa0-b814-57a75559dcef")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("26423bcd-90fe-4fa0-b814-57a75559dcef")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
